# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleimp', '0003_auto_20171116_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termopagto',
            name='termo',
        ),
    ]
