# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:54
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleimp', '0004_remove_termopagto_termo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='termopagto',
            name='termo',
            field=models.IntegerField(default=0),
        ),
    ]
