# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleimp', '0006_remove_cliente_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
