# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleimp', '0007_cliente_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termopagto',
            name='termo',
            field=models.IntegerField(blank=True),
        ),
    ]
