# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleimp', '0008_auto_20171121_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termopagto',
            name='termo',
            field=models.IntegerField(),
        ),
    ]
