# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleimp', '0009_auto_20171121_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
